//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.12 at 04:51:56 PM SAMT 
//


package com.example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Statistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalPasses" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="accuratePasses" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="passAccuracy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="keyPasses" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shotsTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shotsOnTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shotsOffTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shotsBlocked" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shotsAccuracy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="clearances" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="interceptions" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="arialsTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="arialsWon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="arialsSuccesfullPersent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tacklesTry" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tacklesWon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tacklesSuccesfullPersent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="dribblesTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dribblesWon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dribblesSuccesfullPersent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Statistics", propOrder = {
    "rating",
    "totalPasses",
    "accuratePasses",
    "passAccuracy",
    "keyPasses",
    "shotsTotal",
    "shotsOnTarget",
    "shotsOffTarget",
    "shotsBlocked",
    "shotsAccuracy",
    "clearances",
    "interceptions",
    "arialsTotal",
    "arialsWon",
    "arialsSuccesfullPersent",
    "tacklesTry",
    "tacklesWon",
    "tacklesSuccesfullPersent",
    "dribblesTotal",
    "dribblesWon",
    "dribblesSuccesfullPersent"
})
public class Statistics {

    protected double rating;
    protected double totalPasses;
    protected double accuratePasses;
    protected double passAccuracy;
    protected double keyPasses;
    protected double shotsTotal;
    protected double shotsOnTarget;
    protected double shotsOffTarget;
    protected double shotsBlocked;
    protected double shotsAccuracy;
    protected double clearances;
    protected double interceptions;
    protected double arialsTotal;
    protected double arialsWon;
    protected double arialsSuccesfullPersent;
    protected double tacklesTry;
    protected double tacklesWon;
    @XmlElement(required = true)
    protected double tacklesSuccesfullPersent;
    protected double dribblesTotal;
    protected double dribblesWon;
    @XmlElement(required = true)
    protected double dribblesSuccesfullPersent;

    /**
     * Gets the value of the rating property.
     * 
     */
    public double getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(double value) {
        this.rating = value;
    }

    /**
     * Gets the value of the totalPasses property.
     * 
     */
    public double getTotalPasses() {
        return totalPasses;
    }

    /**
     * Sets the value of the totalPasses property.
     * 
     */
    public void setTotalPasses(double value) {
        this.totalPasses = value;
    }

    /**
     * Gets the value of the accuratePasses property.
     * 
     */
    public double getAccuratePasses() {
        return accuratePasses;
    }

    /**
     * Sets the value of the accuratePasses property.
     * 
     */
    public void setAccuratePasses(double value) {
        this.accuratePasses = value;
    }

    /**
     * Gets the value of the passAccuracy property.
     * 
     */
    public double getPassAccuracy() {
        return passAccuracy;
    }

    /**
     * Sets the value of the passAccuracy property.
     * 
     */
    public void setPassAccuracy(double value) {
        this.passAccuracy = value;
    }

    /**
     * Gets the value of the keyPasses property.
     * 
     */
    public double getKeyPasses() {
        return keyPasses;
    }

    /**
     * Sets the value of the keyPasses property.
     * 
     */
    public void setKeyPasses(double value) {
        this.keyPasses = value;
    }

    /**
     * Gets the value of the shotsTotal property.
     * 
     */
    public double getShotsTotal() {
        return shotsTotal;
    }

    /**
     * Sets the value of the shotsTotal property.
     * 
     */
    public void setShotsTotal(double value) {
        this.shotsTotal = value;
    }

    /**
     * Gets the value of the shotsOnTarget property.
     * 
     */
    public double getShotsOnTarget() {
        return shotsOnTarget;
    }

    /**
     * Sets the value of the shotsOnTarget property.
     * 
     */
    public void setShotsOnTarget(double value) {
        this.shotsOnTarget = value;
    }

    /**
     * Gets the value of the shotsOffTarget property.
     * 
     */
    public double getShotsOffTarget() {
        return shotsOffTarget;
    }

    /**
     * Sets the value of the shotsOffTarget property.
     * 
     */
    public void setShotsOffTarget(double value) {
        this.shotsOffTarget = value;
    }

    /**
     * Gets the value of the shotsBlocked property.
     * 
     */
    public double getShotsBlocked() {
        return shotsBlocked;
    }

    /**
     * Sets the value of the shotsBlocked property.
     * 
     */
    public void setShotsBlocked(double value) {
        this.shotsBlocked = value;
    }

    /**
     * Gets the value of the shotsAccuracy property.
     * 
     */
    public double getShotsAccuracy() {
        return shotsAccuracy;
    }

    /**
     * Sets the value of the shotsAccuracy property.
     * 
     */
    public void setShotsAccuracy(double value) {
        this.shotsAccuracy = value;
    }

    /**
     * Gets the value of the clearances property.
     * 
     */
    public double getClearances() {
        return clearances;
    }

    /**
     * Sets the value of the clearances property.
     * 
     */
    public void setClearances(double value) {
        this.clearances = value;
    }

    /**
     * Gets the value of the interceptions property.
     * 
     */
    public double getInterceptions() {
        return interceptions;
    }

    /**
     * Sets the value of the interceptions property.
     * 
     */
    public void setInterceptions(double value) {
        this.interceptions = value;
    }

    /**
     * Gets the value of the arialsTotal property.
     * 
     */
    public double getArialsTotal() {
        return arialsTotal;
    }

    /**
     * Sets the value of the arialsTotal property.
     * 
     */
    public void setArialsTotal(double value) {
        this.arialsTotal = value;
    }

    /**
     * Gets the value of the arialsWon property.
     * 
     */
    public double getArialsWon() {
        return arialsWon;
    }

    /**
     * Sets the value of the arialsWon property.
     * 
     */
    public void setArialsWon(double value) {
        this.arialsWon = value;
    }

    /**
     * Gets the value of the arialsSuccesfullPersent property.
     * 
     */
    public double getArialsSuccesfullPersent() {
        return arialsSuccesfullPersent;
    }

    /**
     * Sets the value of the arialsSuccesfullPersent property.
     * 
     */
    public void setArialsSuccesfullPersent(double value) {
        this.arialsSuccesfullPersent = value;
    }

    /**
     * Gets the value of the tacklesTry property.
     * 
     */
    public double getTacklesTry() {
        return tacklesTry;
    }

    /**
     * Sets the value of the tacklesTry property.
     * 
     */
    public void setTacklesTry(double value) {
        this.tacklesTry = value;
    }

    /**
     * Gets the value of the tacklesWon property.
     * 
     */
    public double getTacklesWon() {
        return tacklesWon;
    }

    /**
     * Sets the value of the tacklesWon property.
     * 
     */
    public void setTacklesWon(double value) {
        this.tacklesWon = value;
    }

    /**
     * Gets the value of the tacklesSuccesfullPersent property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public double getTacklesSuccesfullPersent() {
        return tacklesSuccesfullPersent;
    }

    /**
     * Sets the value of the tacklesSuccesfullPersent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTacklesSuccesfullPersent(double value) {
        this.tacklesSuccesfullPersent = value;
    }

    /**
     * Gets the value of the dribblesTotal property.
     * 
     */
    public double getDribblesTotal() {
        return dribblesTotal;
    }

    /**
     * Sets the value of the dribblesTotal property.
     * 
     */
    public void setDribblesTotal(double value) {
        this.dribblesTotal = value;
    }

    /**
     * Gets the value of the dribblesWon property.
     * 
     */
    public double getDribblesWon() {
        return dribblesWon;
    }

    /**
     * Sets the value of the dribblesWon property.
     * 
     */
    public void setDribblesWon(double value) {
        this.dribblesWon = value;
    }

    /**
     * Gets the value of the dribblesSuccesfullPersent property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public double getDribblesSuccesfullPersent() {
        return dribblesSuccesfullPersent;
    }

    /**
     * Sets the value of the dribblesSuccesfullPersent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDribblesSuccesfullPersent(double value) {
        this.dribblesSuccesfullPersent = value;
    }

}
